### ISSUE TITLE
can you offer some example data sets for a test?

### ISSUE THREAD

**Issue by Huanle** [mrmckain/FASTKs#1]

**Comment by mrmckain** [comment]
I added an example dataset and have expanded the README.  I will complete the update on the README and in the code on October 13, 2016.

**Comment by Huanle** [comment]
Thanks a lot.

**Comment by mrmckain** [comment]
I believe that everything you need is now uploaded.  I have uploaded a codeml.ctl file that FASTKs uses to run codeml in PAML.  I have also packaged pal2nal with FASTKs for converted peptide alignments to codon.  Please let me know if you have any problems.
